version: '3.9'

networks:
  dev:

services:
  frontend:
    build:
      context: .
      dockerfile: train-service-client/Dockerfile
    depends_on:
      - backend
    networks:
      - dev
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Train Service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dev

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      - dev
