name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: cd "Train Service" && dotnet restore
    - name: Build
      run: cd "Train Service" && dotnet build --no-restore
    - name: Test
      run: cd "Train Service" && dotnet test --no-build --verbosity normal